version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: <your_db_name> 
      POSTGRES_PASSWORD: <your_db_password> 
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb
